name: code check
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: bundle install
      run: bundle install
    - name: rubocop
      run: bundle exec rubocop
    - name: Rspec
      run: bundle exec rspec
